#!/bin/bash
if [ "$(lsb_release -si)" != "Ubuntu" ]
then
	echo "Your operating system is not supported! Abort."
	exit 1
fi

if [ "$USERNAME" == "root" ]
then
	echo "Please do not execute this script as root! Abort."
	exit 1
fi

VERSION_CODE_NAME=$(lsb_release -sc)

# this function is only used by add_repositories()
function addAptRepositories() {
	# PPA for wine
	#add-apt-repository -y ppa:ubuntu-wine/ppa
	# PPA for VLC player
	#add-apt-repository -y ppa:videolan/stable-daily
	# PPA for Guayadeque media player
	#add-apt-repository -y ppa:anonbeat/guayadeque
	# PPA for ffmpeg
	#add-apt-repository -y ppa:jon-severinsson/ffmpeg
	# PPA for Oracle Java
	#sudo add-apt-repository ppa:webupd8team/java
	
	sudo apt-add-repository ppa:webupd8team/java
	sudo apt-add-repository ppa:strukturag/libde265 # only required for Ubuntu <= 14.04
	sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
	
	sudo apt-get update
}

# install all media codecs for gstreamer + mozilla plugin
function installMediaCodecs() {
	sudo apt-get -y install ubuntu-restricted-extras
}

function installUtils() {
	sudo apt-get -y install rar p7zip optipng wine ttf-mscorefonts-installer fonts-sil-gentium nautilus-open-terminal nautilus-gtkhash gparted libreoffice-gtk3 libreoffice-style-sifr libreoffice-pdfimport libreoffice-ogltrans libreoffice-presenter-console libreoffice-presentation-minimizer
}

# install different useful tools that are not provided by default
function installMisc() {
	sudo apt-get -y remove empathy # remove unused components
	sudo apt-get -y install inkscape gimp gthumb filezilla pidgin pidgin-otr skype4pidgin vlc
}

function installDevTools() {
	sudo apt-get -y install build-essential ubuntu-make oracle-java8-installer
}

function installGnomeShell() {
	sudo apt-get -y install gnome-shell gnome-tweak-tool menulibre redshift-gtk
}

function installLatex() {
	sudo apt-get -y install libreoffice-writer2latex texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-extra-utils
}

function installAnthy() {
	sudo apt-get -y install anthy ibus-anthy language-pack-ja language-pack-ja-base language-pack-gnome-ja-base language-pack-gnome-ja kanjipad
}

function configureGnomeSettings() {
	gsettings set org.gnome.nautilus.preferences default-sort-order type # set default file order to 'by type'
	gsettings set org.gnome.nautilus.preferences executable-text-activation ask # allow scripts to be executed by double-click (dialog)
	gsettings set org.gnome.gedit.preferences.editor display-line-numbers true # display line numbers in gedit
	gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
	gsettings set org.gnome.gedit.preferences.editor bracket-matching true
	gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'
	gsettings set org.gnome.gedit.preferences.editor auto-indent true
}

## MAIN ##

# create font directory for user defined truetype fonts
if [ ! -d "/usr/share/fonts/truetype/ttf-extra" ]
then
	sudo mkdir -m 744 /usr/share/fonts/truetype/ttf-extra
fi

# install aptitude if it's not already installed
if [ ! -f "/usr/bin/aptitude" ]
then
	sudo apt-get -y install aptitude
fi

configureGnomeSettings
addAptRepositories

installGnomeShell
installUtils
installMediaCodecs
installMisc
installDevTools
#installAnthy # install japanese extensions
#installLatex # install texlive environment

sudo apt-get --force-yes -y dist-upgrade # update packages
sudo apt-get -y autoremove # remove unused packages

echo "Ubuntu setup is done."

