#!/bin/bash
if [ "$(lsb_release -si)" != "Ubuntu" ]
then
	echo "Your operating system is not supported! Abort."
	exit 1
fi

if [ "$USERNAME" == "root" ]
then
	echo "Please do not execute this script as root! Abort."
	exit 1
fi

VERSION_CODE_NAME=$(lsb_release -sc)

function addAptRepositories() {
	if [ ! -f "/usr/bin/curl" ]
	then
		sudo apt install -y curl
	fi

	# install repo for VSCode
	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
	sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
	sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

	# install repo for Node.js
	curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

	sudo apt update
}

function installMediaCodecs() {
	# installs all media codecs for gstreamer + mozilla plugin
	sudo apt install -y ubuntu-restricted-extras
}

function installUtils() {
	sudo apt install -y net-tools curl rar p7zip-full keepass2 pwgen nautilus-gtkhash gparted optipng fonts-sil-gentium libreoffice-gtk3 libreoffice-style-sifr libreoffice-pdfimport libreoffice-ogltrans
}

# install different useful tools that are not provided by default
function installMisc() {
	sudo apt install -y inkscape gimp gthumb totem filezilla pidgin pidgin-otr vlc thunderbird thunderbird-gnome-support transmission-gtk
}

function installDevTools() {
	sudo apt install -y build-essential openjdk-11-jdk nodejs git code
	sudo npm install -g @angular/cli
}

function installGnomeShell() {
	sudo apt install -y gnome-shell gnome-session gnome-tweak-tool menulibre
	echo "--> Manually select '/usr/share/gnome-shell/theme/gnome-shell.css':"
	sudo update-alternatives --config gdm3.css
}

function installRedshift() {
	geoclue_conf="/etc/geoclue/geoclue.conf"
	sudo apt install -y redshift-gtk

	sudo sh -c "echo >> $geoclue_conf"
	sudo sh -c "echo '[redshift]' >> $geoclue_conf"
	sudo sh -c "echo 'allowed=true' >> $geoclue_conf"
	sudo sh -c "echo 'system=false' >> $geoclue_conf"
	sudo sh -c "echo 'users=' >> $geoclue_conf"
}

function installLaptopModeTools() {
	sudo apt install -y tlp tlp-rdw
	# start with: sudo tlp start
}

#function installWine() {
	#TODO implement
	#sudo apt install -y wine-stable
#}

function installLatex() {
	sudo apt install -y libreoffice-writer2latex texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-extra-utils
}

function installAnthy() {
	sudo apt install -y anthy ibus-anthy language-pack-ja language-pack-ja-base language-pack-gnome-ja-base language-pack-gnome-ja kanjipad
}

function configureGnomeSettings() {
	gsettings set org.gnome.nautilus.preferences default-sort-order 'type'
	gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'

	gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
	gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
	gsettings set org.gnome.gedit.preferences.editor bracket-matching true
	gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'
	gsettings set org.gnome.gedit.preferences.editor auto-indent true
	gsettings set org.gnome.gedit.preferences.editor tabs-size 'uint32 2'
}

function disableSystemShortcuts() {
	gsettings set org.gnome.desktop.wm.keybindings toggle-shaded '[]'
	gsettings set org.gnome.desktop.wm.keybindings begin-move '[]'
	gsettings set org.gnome.desktop.wm.keybindings panel-main-menu '[]'
}

function createCustomFontDirectory() {
	# create font directory for user defined truetype fonts
	if [ ! -d "/usr/share/fonts/truetype/ttf-extra" ]
	then
		sudo mkdir -m 744 /usr/share/fonts/truetype/ttf-extra
	fi
}

## MAIN ##

sudo apt update
#addAptRepositories

#installGnomeShell
#installRedshift
#installLaptopModeTools
#installUtils
#installMediaCodecs
#installMisc
#installDevTools
#installAnthy # install japanese extensions
#installLatex # install texlive environment

#createCustomFontDirectory
#configureGnomeSettings
#disableSystemShortcuts

sudo apt update && sudo apt upgrade -y # update all install packages
sudo apt autoremove -y # remove unused packages

echo "Ubuntu setup is done."

