#!/usr/bin/python
# -*- coding: utf-8 -*-
WORD_COLLECTION_EN = set(sorted([
	  u'a pregnant pause'
	, u'abashed'
	, u'acquaintance'
	, u'aggravating'
	, u'aggrieved'
	, u'aghast'
	, u'agitated'
	, u'agonising'
	, u'airily'
	, u'amber'
	, u'amicably'
	, u'amid'
	, u'animosity'
	, u'antagonizing'
	, u'antics'
	, u'appalled'
	, u'appraisingly'
	, u'apprehensively'
	, u'apprentice'
	, u'aquiver'
	, u'archway'
	, u'askance'
	, u'askew'
	, u'asperity'
	, u'assent'
	, u'astray'
	, u'astride'
	, u'at either end'
	, u'at large'
	, u'austere'
	, u'awestruck'
	, u'axle grease'
	, u'balaclava'
	, u'banshee'
	, u'barmy'
	, u'barter'
	, u'bated'
	, u'battered'
	, u'bauble'
	, u'beacon'
	, u'beckoning'
	, u'bedlam'
	, u'bedraggled'
	, u'benignly'
	, u'berth'
	, u'bigotry'
	, u'bird of prey'
	, u'blandly'
	, u'blazing row'
	, u'blemishes'
	, u'blistering'
	, u'bloke'
	, u'blunder'
	, u'blundering'
	, u'bog'
	, u'bogey'
	, u'boisterous'
	, u'bonnet'
	, u'boughs'
	, u'boulder'
	, u'brass'
	, u'breezy'
	, u'brim'
	, u'briskly'
	, u'bungler'
	, u'burrow'
	, u'burrowed'
	, u'cane'
	, u'canopy'
	, u'cauldron'
	, u'chappie'
	, u'charm'
	, u'chipped'
	, u'chisel'
	, u'chivalry'
	, u'chuffed'
	, u'cinch'
	, u'clairvoyant'
	, u'cloak'
	, u'codger'
	, u'coil'
	, u'commiserating'
	, u'commodity'
	, u'commotion'
	, u'comprehensive'
	, u'compulsory'
	, u'concealment'
	, u'condemnation'
	, u'conduct'
	, u'contemptuous'
	, u'convulsive'
	, u'copper'
	, u'counseling'
	, u'cowardice'
	, u'crate'
	, u'crescendo'
	, u'crest'
	, u'crestfallen'
	, u'crisply'
	, u'crowing'
	, u'culprit'
	, u'cunning'
	, u'curious'
	, u'curtly'
	, u'custard'
	, u'deduction'
	, u'dejectedly'
	, u'deliberate'
	, u'deprived'
	, u'derisive'
	, u'detention'
	, u'devoid'
	, u'diatribe'
	, u'diminished'
	, u'disdainful'
	, u'disgruntled'
	, u'distended'
	, u'distinct'
	, u'diversion'
	, u'dodgy'
	, u'dolefully'
	, u'don\'t everybody speak up at once!'
	, u'dormice'
	, u'dottiness'
	, u'downtrodden'
	, u'draught'
	, u'draughty'
	, u'drawer'
	, u'drawling'
	, u'dreadful'
	, u'dregs'
	, u'drenched'
	, u'duffer'
	, u'dusk'
	, u'eerie'
	, u'elaborate'
	, u'emaciated'
	, u'emblazoned'
	, u'emerald'
	, u'enclosure'
	, u'engorgement'
	, u'engulfed'
	, u'enraptured'
	, u'enticing'
	, u'entwined'
	, u'exasperated'
	, u'exuberant'
	, u'fainted'
	, u'fervent'
	, u'feverishly'
	, u'flabbergasted'
	, u'fleet'
	, u'flight of stairs'
	, u'fluke'
	, u'flustered'
	, u'fondly'
	, u'fortnight'
	, u'frame-up'
	, u'frantic'
	, u'fringe'
	, u'fudge'
	, u'fugitive'
	, u'furling'
	, u'furtive'
	, u'gales of laughter'
	, u'gallant'
	, u'galvanised'
	, u'gamekeeper'
	, u'gash'
	, u'gaunt'
	, u'gawping'
	, u'gaze'
	, u'gibbon'
	, u'gills'
	, u'gingerly'
	, u'glee'
	, u'gloomily'
	, u'glowering'
	, u'goblets'
	, u'gouge'
	, u'gravely'
	, u'gravy'
	, u'griffin'
	, u'grisly'
	, u'grubby'
	, u'gruffly'
	, u'guffaw'
	, u'guile'
	, u'hag'
	, u'hampered'
	, u'harebrained'
	, u'harness'
	, u'havoc'
	, u'hearthrug'
	, u'hedgehog'
	, u'heinous'
	, u'henceforth'
	, u'hewn'
	, u'hilt'
	, u'hinge'
	, u'hitch'
	, u'hitherto'
	, u'hoarse'
	, u'holly'
	, u'hoodwinked'
	, u'huddle'
	, u'humongous'
	, u'hunchback'
	, u'hunched'
	, u'impeccably'
	, u'imperiously'
	, u'imploringly'
	, u'incantation'
	, u'incidentally'
	, u'indignantly'
	, u'indispensable'
	, u'indisposed'
	, u'inept'
	, u'inquiry'
	, u'inscrutable'
	, u'insurmountable'
	, u'interrogating'
	, u'intrigued'
	, u'irksome'
	, u'jauntily'
	, u'jaunty'
	, u'javelin'
	, u'jig'
	, u'jowl'
	, u'kettle'
	, u'knack'
	, u'laden'
	, u'landing'
	, u'lap of honor'
	, u'lavatory seat'
	, u'layabout'
	, u'legible'
	, u'lenient'
	, u'lest'
	, u'liability'
	, u'lofty'
	, u'longingly'
	, u'lopsided'
	, u'lot'
	, u'ludicrous'
	, u'lumbago'
	, u'lump'
	, u'maddening'
	, u'makeshift'
	, u'malice'
	, u'manacle'
	, u'mantelpiece'
	, u'manure'
	, u'marble'
	, u'marsh'
	, u'mead'
	, u'meadow'
	, u'meddlesome'
	, u'menace'
	, u'menacing'
	, u'mingled'
	, u'mirthless'
	, u'misty'
	, u'mongrel'
	, u'moodily'
	, u'moral fibre'
	, u'mortal peril'
	, u'mulishly'
	, u'mundane'
	, u'mutinous'
	, u'nonplussed'
	, u'nostrils'
	, u'nosy'
	, u'oaf'
	, u'objection'
	, u'offhand'
	, u'old-fangled'
	, u'omission'
	, u'ordeal'
	, u'outskirts'
	, u'overt'
	, u'pace'
	, u'paddock'
	, u'pallid'
	, u'paramount'
	, u'parchment'
	, u'parlour'
	, u'patch'
	, u'paving'
	, u'pebbles'
	, u'peckish'
	, u'pelting'
	, u'penance'
	, u'pensively'
	, u'perch'
	, u'perchance'
	, u'perturbed'
	, u'petrified'
	, u'petulantly'
	, u'pewter'
	, u'pheasant'
	, u'phial'
	, u'pillock'
	, u'pincers'
	, u'pinprick'
	, u'pinstriped'
	, u'plinth'
	, u'plumbing'
	, u'plus fours'
	, u'poker'
	, u'polecat'
	, u'porridge'
	, u'portly'
	, u'potholes'
	, u'precarious'
	, u'premeditated'
	, u'premise'
	, u'premonition'
	, u'preposterous'
	, u'preserve'
	, u'profusely'
	, u'prong'
	, u'protruding'
	, u'protuberant'
	, u'provision'
	, u'prowling'
	, u'prudent'
	, u'pug'
	, u'pummeling'
	, u'punitive'
	, u'putrid'
	, u'puzzlement'
	, u'quagmire'
	, u'queasy'
	, u'quick-witted'
	, u'quill'
	, u'raccoon'
	, u'rag doll'
	, u'rancid'
	, u'rapturously'
	, u'raspberry'
	, u'rattled'
	, u'raucous'
	, u'ravine'
	, u'receding'
	, u'rein'
	, u'relish'
	, u'remedy'
	, u'reminiscent'
	, u'remnant'
	, u'remorse'
	, u'reproachful'
	, u'reprovingly'
	, u'resemblance'
	, u'resentment'
	, u'retaliation'
	, u'retention'
	, u'reverie'
	, u'revulsion'
	, u'rickety'
	, u'riddle'
	, u'rigid'
	, u'rooster'
	, u'ruffled'
	, u'rug'
	, u'rummaging'
	, u'sanctimoniously'
	, u'saucer'
	, u'savagely'
	, u'savouring'
	, u'sb. humbugs'
	, u'sb. purports'
	, u'scabbard'
	, u'scarlet'
	, u'scathing'
	, u'scowling'
	, u'scrounger'
	, u'scudding'
	, u'scuffle'
	, u'seal'
	, u'search me.'
	, u'secluded'
	, u'seething'
	, u'shallow'
	, u'shamrock'
	, u'shan\'t'
	, u'sheaf'
	, u'shifty'
	, u'shrub'
	, u'silkily'
	, u'sinew'
	, u'slab'
	, u'slain'
	, u'slithering'
	, u'sliver'
	, u'slog'
	, u'sluggish'
	, u'sly'
	, u'smirk'
	, u'snuff box'
	, u'solemnly'
	, u'sombre'
	, u'somersault'
	, u'soot'
	, u'sore'
	, u'spasm'
	, u'spectacles'
	, u'spinning top'
	, u'spotty'
	, u'sprouts'
	, u'spunky'
	, u'squashy'
	, u'squeal'
	, u'squid'
	, u'squirt'
	, u'stag'
	, u'stagecoach'
	, u'staggered'
	, u'startled'
	, u'steering'
	, u'stern'
	, u'stifling'
	, u'stoat'
	, u'strain'
	, u'subdued'
	, u'sullenness'
	, u'supple'
	, u'surly'
	, u'swarthy'
	, u'swathed'
	, u'swiftly'
	, u'talon'
	, u'tankard'
	, u'tantrum'
	, u'tap'
	, u'tawny'
	, u'teeming'
	, u'tentatively'
	, u'tenterhook'
	, u'tersely'
	, u'testily'
	, u'tetchy'
	, u'tethered'
	, u'thatched'
	, u'threshold'
	, u'thud'
	, u'tichy'
	, u'timidly'
	, u'to attain'
	, u'to bait'
	, u'to bask'
	, u'to be all of a dither'
	, u'to be delicate'
	, u'to be immersed'
	, u'to be just doing sth.'
	, u'to be keen on sth.'
	, u'to be over the moon with sth.'
	, u'to be startled'
	, u'to be up to scratch'
	, u'to be wary of sb./sth.'
	, u'to be well shot of sb.'
	, u'to beam'
	, u'to beckon'
	, u'to bellow'
	, u'to bequeath'
	, u'to bestow'
	, u'to betide'
	, u'to blanch'
	, u'to blow sb. a raspberry'
	, u'to blush'
	, u'to boom'
	, u'to brandish'
	, u'to budge up'
	, u'to cackle'
	, u'to canter'
	, u'to catcall'
	, u'to catch sb. red-handed'
	, u'to cheek sb.'
	, u'to chortle'
	, u'to clasp'
	, u'to clout'
	, u'to clutch'
	, u'to collude'
	, u'to commend'
	, u'to commute'
	, u'to conceal'
	, u'to confine'
	, u'to congregate'
	, u'to conjure'
	, u'to consent'
	, u'to convey'
	, u'to crease'
	, u'to culminate'
	, u'to daze'
	, u'to deceive'
	, u'to defer'
	, u'to demise'
	, u'to dent'
	, u'to deprive'
	, u'to desist'
	, u'to despise'
	, u'to detain'
	, u'to detest'
	, u'to diminish'
	, u'to discern'
	, u'to disembowel'
	, u'to dispatch'
	, u'to dispense'
	, u'to divulge'
	, u'to double back'
	, u'to double up'
	, u'to dread'
	, u'to each his own'
	, u'to eavesdrop'
	, u'to egg sb. on'
	, u'to elude'
	, u'to emblazon'
	, u'to emerge'
	, u'to ensnare'
	, u'to exclaim'
	, u'to expel'
	, u'to faint'
	, u'to falter'
	, u'to fancy'
	, u'to fathom'
	, u'to feint'
	, u'to fidget'
	, u'to flay'
	, u'to flinch'
	, u'to forage'
	, u'to forfeit'
	, u'to frame sb.'
	, u'to fraternise'
	, u'to fret (about)'
	, u'to fume (at sb.)'
	, u'to gape'
	, u'to get a dose of the clap'
	, u'to give a leap'
	, u'to give a start'
	, u'to glance'
	, u'to gloat'
	, u'to gnarl'
	, u'to go haywire'
	, u'to go into the matter'
	, u'to grow on sb.'
	, u'to haggle'
	, u'to have a row with sb.'
	, u'to heed'
	, u'to hiss'
	, u'to hoist sb. off'
	, u'to hoodwink'
	, u'to impair'
	, u'to impede'
	, u'to incline'
	, u'to insulate'
	, u'to jeer'
	, u'to jerk'
	, u'to jinx'
	, u'to jostle'
	, u'to know sb. of old'
	, u'to learn sth. (off) by heart'
	, u'to leer'
	, u'to limp'
	, u'to lodge'
	, u'to look harassed'
	, u'to loom up'
	, u'to lumber'
	, u'to lurch'
	, u'to make a beeline for sb./sth.'
	, u'to make a run for it'
	, u'to meddle'
	, u'to mend'
	, u'to mesmerise'
	, u'to moult'
	, u'to nag'
	, u'to neglect'
	, u'to ogle'
	, u'to peck'
	, u'to peer'
	, u'to pelt'
	, u'to perish'
	, u'to pervade'
	, u'to pestle sth.'
	, u'to plummet'
	, u'to pour'
	, u'to precede'
	, u'to preen'
	, u'to prevail'
	, u'to proclaim'
	, u'to prod'
	, u'to protrude'
	, u'to prowl'
	, u'to prune'
	, u'to purse'
	, u'to quail'
	, u'to quiver'
	, u'to recede'
	, u'to reel off sth.'
	, u'to refrain from sth.'
	, u'to rejoice'
	, u'to renounce'
	, u'to replenish'
	, u'to resemble'
	, u'to restrain'
	, u'to retort'
	, u'to rev'
	, u'to reverence'
	, u'to ricochet'
	, u'to rifle through'
	, u'to sack sb.'
	, u'to scarper'
	, u'to scoff'
	, u'to scoop'
	, u'to scorn sth.'
	, u'to scowl'
	, u'to scramble'
	, u'to scurry'
	, u'to scuttle off'
	, u'to see sb. off'
	, u'to seize'
	, u'to shuffle away'
	, u'to shunt'
	, u'to simper'
	, u'to skid'
	, u'to smother'
	, u'to snarl'
	, u'to sneer'
	, u'to snigger'
	, u'to soothe'
	, u'to spiff up'
	, u'to spin sth. off'
	, u'to splutter'
	, u'to sprain'
	, u'to square sb.'
	, u'to squelch'
	, u'to squint'
	, u'to stagger'
	, u'to steady'
	, u'to stride'
	, u'to suffocate'
	, u'to surmise'
	, u'to survey'
	, u'to swagger'
	, u'to swill'
	, u'to swivel'
	, u'to take a leaf out of sbs. book'
	, u'to take sbs. mind off sth.'
	, u'to take the measure of sb.'
	, u'to take the mickey out of sb.'
	, u'to tally'
	, u'to tamper'
	, u'to tarry'
	, u'to tell on sb.'
	, u'to tell sb. off'
	, u'to tether'
	, u'to throng'
	, u'to tingle'
	, u'to tremble'
	, u'to trudge'
	, u'to trundle'
	, u'to twinkle'
	, u'to twitch'
	, u'to usher'
	, u'to ward off'
	, u'to weep'
	, u'to wince'
	, u'to wriggle'
	, u'to writhe'
	, u'to yearn'
	, u'to yield to tempation'
	, u'toad'
	, u'toil'
	, u'tomboy'
	, u'torpor'
	, u'torrent'
	, u'treaty'
	, u'tremulous'
	, u'trench'
	, u'trepidation'
	, u'trespassing'
	, u'tripe'
	, u'trunk'
	, u'turret'
	, u'twinge'
	, u'twitching'
	, u'tyke'
	, u'uncanny'
	, u'unctuous'
	, u'undergrowth'
	, u'undiluted'
	, u'unflinching'
	, u'ungiving'
	, u'unperturbed'
	, u'unscathed'
	, u'velvety'
	, u'verdict'
	, u'vermin'
	, u'veterinarian'
	, u'vicar'
	, u'vindicating'
	, u'vindictiveness'
	, u'vivacious'
	, u'vividly'
	, u'vulture'
	, u'waft'
	, u'ward'
	, u'warlock'
	, u'waspishly'
	, u'wearily'
	, u'weedy'
	, u'well-groomed'
	, u'wheezing'
	, u'whisker'
	, u'whomp'
	, u'whoop'
	, u'wickerwork'
	, u'wig'
	, u'willow'
	, u'wistfully'
	, u'wit'
	, u'withering'
	, u'woe'
	, u'woebegone'
	, u'wolverine'
	, u'wreath'
	, u'wryly'
	, u'yelp'
	, u'abrasive'
	, u'abstaining'
	, u'adamant'
	, u'affiliation'
	, u'ahold'
	, u'aisle'
	, u'akin'
	, u'alumnus'
	, u'amicable'
	, u'aneurysm'
	, u'bankroll'
	, u'blip'
	, u'botched'
	, u'breach'
	, u'budge'
	, u'bumper'
	, u'burr'
	, u'cadence'
	, u'carter'
	, u'caucus'
	, u'chicken-shit'
	, u'chitlins'
	, u'coaster'
	, u'cogent'
	, u'compelling'
	, u'condescending'
	, u'constituents'
	, u'contender'
	, u'contention'
	, u'conure'
	, u'coroner'
	, u'courting'
	, u'cramming'
	, u'cub'
	, u'dago'
	, u'dangling'
	, u'decaf'
	, u'detox'
	, u'diligence'
	, u'dime'
	, u'dipping'
	, u'dissemination'
	, u'dissipated'
	, u'distaste'
	, u'diverted'
	, u'docket'
	, u'duke'
	, u'earmarked'
	, u'edification'
	, u'embroiled'
	, u'eminent'
	, u'evicted'
	, u'filibuster'
	, u'fiscal'
	, u'fixture'
	, u'flattered'
	, u'fling'
	, u'flip-flopping'
	, u'folksy'
	, u'formidable'
	, u'forthcoming'
	, u'forthright'
	, u'frenzy'
	, u'gaffe'
	, u'gauntlet'
	, u'girth'
	, u'gist'
	, u'gravitas'
	, u'gritty'
	, u'gutter'
	, u'hatchback'
	, u'haul'
	, u'hazed'
	, u'holdout'
	, u'hubris'
	, u'impeachment'
	, u'inaugural'
	, u'incendiary'
	, u'incentive'
	, u'incessant'
	, u'inclined'
	, u'indelibly'
	, u'indelicate'
	, u'indentured'
	, u'inebriated'
	, u'intercom'
	, u'interstate'
	, u'invigorating'
	, u'junket'
	, u'knobs'
	, u'lassitude'
	, u'latched'
	, u'lectern'
	, u'ledger'
	, u'leper'
	, u'libertarian'
	, u'livelihood'
	, u'livid'
	, u'loitering'
	, u'luncheon'
	, u'mainline'
	, u'masthead'
	, u'materiel'
	, u'matriculated'
	, u'mumbling'
	, u'municipal'
	, u'municipalities'
	, u'murmuring'
	, u'murmurs'
	, u'nappies'
	, u'negligence'
	, u'negligible'
	, u'op-ed'
	, u'opec'
	, u'opinionated'
	, u'overture'
	, u'pageant'
	, u'pancreas'
	, u'pasture'
	, u'paved'
	, u'pedestal'
	, u'peg'
	, u'persuasion'
	, u'petite'
	, u'pettiness'
	, u'picket'
	, u'planks'
	, u'ploy'
	, u'plumber'
	, u'poaching'
	, u'point-blank'
	, u'precedent'
	, u'preeminence'
	, u'preliminary'
	, u'primaries'
	, u'prob'
	, u'prop'
	, u'pry'
	, u'puff'
	, u'quarrelsome'
	, u'ravished'
	, u'reins'
	, u'relapsed'
	, u'renegade'
	, u'retching'
	, u'retribution'
	, u'rogue'
	, u'rotunda'
	, u'rustling'
	, u'savvy'
	, u'scapegoat'
	, u'schmoozer'
	, u'scolding'
	, u'scout'
	, u'sentinel'
	, u'shackle'
	, u'sham'
	, u'shenanigans'
	, u'shutters'
	, u'slack'
	, u'sledgehammer'
	, u'sludge'
	, u'slugline'
	, u'slurred'
	, u'sobriety'
	, u'solace'
	, u'solicitation'
	, u'solitary'
	, u'sophomore'
	, u'spawned'
	, u'spearheaded'
	, u'sphincter'
	, u'spur-of-the-moment'
	, u'staffer'
	, u'stalemate'
	, u'stammering'
	, u'star-spangled'
	, u'stature'
	, u'stray'
	, u'sublime'
	, u'submission'
	, u'subpoena'
	, u'subsidiaries'
	, u'subsidies'
	, u'supremacy'
	, u'sway'
	, u'swoop'
	, u'tad'
	, u'tame'
	, u'tenants'
	, u'thrush'
	, u'thuds'
	, u'thumping'
	, u'thunderclap'
	, u'to avail'
	, u'to backstab sb.'
	, u'to be bogged'
	, u'to berate'
	, u'to churn'
	, u'to clank'
	, u'to clatter'
	, u'to cobble'
	, u'to convene'
	, u'to cuss'
	, u'to dampen'
	, u'to deplore'
	, u'to devour'
	, u'to dismantle'
	, u'to disrupt'
	, u'to dissuade'
	, u'to dredge'
	, u'to exemplify'
	, u'to exempt'
	, u'to forestall'
	, u'to hump'
	, u'to itemize'
	, u'to kindle'
	, u'to mangle'
	, u'to mimeograph'
	, u'to mull'
	, u'to muster'
	, u'to nosedive'
	, u'to persuade'
	, u'to pitter-patter'
	, u'to ream'
	, u'to refine'
	, u'to reinvigorate'
	, u'to relinquish'
	, u'to schmooze'
	, u'to scoff'
	, u'to screech'
	, u'to solicit'
	, u'to stall'
	, u'to steamroll'
	, u'to stonewall sb.'
	, u'to swerve'
	, u'to tweet'
	, u'to twiddle'
	, u'to unbuckle'
	, u'to vacillate'
	, u'to woo'
	, u'to wrench'
	, u'torpedoing'
	, u'traction'
	, u'trailblazer'
	, u'treading'
	, u'trilateral'
	, u'tutelage'
	, u'twat'
	, u'uncouth'
	, u'uppity'
	, u'valedictorian'
	, u'valiant'
	, u'varsity'
	, u'vassal'
	, u'vetted'
	, u'viable'
	, u'vigilance'
	, u'vindictive'
	, u'vines'
	, u'virtues'
	, u'voracious'
	, u'wacko'
	, u'wantonness'
	, u'watershed'
	, u'wheeler'
	, u'whimpering'
	, u'whirring'
	, u'wholly'
	, u'whooping'
	, u'yadda yadda yadda'
	, u'yapping'
	, u'yelping'
]))
